const jobListingsData = [
  {
    id: 1,
    title: 'Horticulturist',
    description: 'Unpot and claw at various plant species in a greenhouse setting.',
    industry: 'Horticulture & Botany',
    location: 'Seattle, WA',
    experience: 'Entry Level',
    environment: 'Onsite',
    salary: '$50,000 - $60,000',
    employmentType: 'Full Time',
  },
  {
    id: 2,
    title: 'Human Leader',
    description: 'Lead a team of humans in a fast-paced work environment so they follow your slow-paced cat environment.',
    industry: 'Leadership',
    location: 'New York, NY',
    experience: 'Executive Level',
    environment: 'Onsite',
    salary: '$300,000 - $400,000',
    employmentType: 'Full Time',
  },
  {
    id: 3,
    title: 'Food Critic',
    description: 'Sample and review various types of cat food and treats.',
    industry: 'Gastronomy',
    location: 'San Francisco, CA',
    experience: 'Mid Level',
    environment: 'Mixed',
    salary: '$70,000 - $90,000',
    employmentType: 'Full Time',
  },
  {
    id: 4,
    title: 'Electrician/Wiring Expert',
    description: 'Chew and swat at electrical systems and wiring.',
    industry: 'Home Maintenance',
    location: 'Houston, TX',
    experience: 'Senior Level',
    environment: 'Onsite',
    salary: '$100,000 - $120,000',
    employmentType: 'Full Time',
  },
  {
    id: 5,
    title: 'Pest Exterminator',
    description: 'Identify and eliminate pests in residential and commercial spaces.',
    industry: 'Security & Safety',
    location: 'Miami, FL',
    experience: 'Entry Level',
    environment: 'Onsite',
    salary: '$50,000 - $60,000',
    employmentType: 'Full Time',
  },
  {
    id: 6,
    title: 'Secret Agent',
    description: 'Complete covert missions and gather intelligence.',
    industry: 'Security & Safety',
    location: 'Washington, D.C.',
    experience: 'Executive Level',
    environment: 'Mixed',
    salary: '$500,000+',
    employmentType: 'Full Time',
  },
  {
    id: 7,
    title: 'Furniture Deconstructor',
    description: 'Destroy furniture to ensure it is cat-proof.',
    industry: 'Home Maintenance',
    location: 'Los Angeles, CA',
    experience: 'Entry Level',
    environment: 'Onsite',
    salary: '$50,000 - $60,000',
    employmentType: 'Full Time',
  },
  {
    id: 8,
    title: 'Ornithologist',
    description: 'Study bird behavior and ecology.',
    industry: 'Nature & Environment',
    location: 'Portland, OR',
    experience: 'Mid Level',
    environment: 'Onsite',
    salary: '$80,000 - $100,000',
    employmentType: 'Full Time',
  },
  {
    id: 9,
    title: 'Private Investigator',
    description: 'Investigate and gather evidence for legal cases.',
    industry: 'Security & Safety',
    location: 'Boston, MA',
    experience: 'Mid Level',
    environment: 'Mixed',
    salary: '$90,000 - $110,000',
    employmentType: 'Part Time',
  },
  {
    id: 10,
    title: 'Pest Exterminator',
    description: 'Seeking an experienced Pest Exterminator to join our team. You will be responsible for identifying, eliminating and preventing pest infestations. Successful candidates will have a proven track record of pest control and knowledge of safe handling and application of pesticides. Must be able to work in a fast-paced environment and have excellent communication and problem-solving skills.',
    industry: 'Home Maintenance',
    location: 'Chicago, IL',
    experience: 'Mid level',
    environment: 'Onsite',
    salary: '$70,000-$90,000',
    employmentType: 'Full time',
  },
  {
    id: 11,
    title: 'Horticulturist',
    description: 'We are seeking a skilled and knowledgeable Horticulturist to join our team. You will be responsible for planning and implementing various horticulture projects, managing a team of gardeners, and maintaining the health and appearance of plants and trees. Successful candidates will have a degree in horticulture or related field, several years of experience in the field, and a passion for environmental sustainability.',
    industry: 'Horticulture & Botany',
    location: 'San Francisco, CA',
    experience: 'Senior level',
    environment: 'Onsite',
    salary: '$120,000-$150,000',
    employmentType: 'Full time',
  },
  {
    id: 12,
    title: 'Private Investigator',
    description: 'Our private investigation firm is seeking a highly experienced and professional Private Investigator to join our team. You will be responsible for conducting surveillance, gathering evidence, and preparing reports for clients. Successful candidates will have a background in law enforcement or military intelligence, excellent communication and problem-solving skills, and the ability to work independently and maintain confidentiality.',
    industry: 'Security & Safety',
    location: 'New York, NY',
    experience: 'Executive level',
    environment: 'Mixed',
    salary: '$250,000-$350,000',
    employmentType: 'Full time',
  },
  {
    id: 13,
    title: 'Furniture Deconstructor',
    description: 'We are seeking a Furniture Deconstructor to join our team. You will be responsible for breaking down furniture into its component parts for recycling and disposal. Successful candidates will have experience with hand and power tools, knowledge of different types of materials and how to safely dismantle them, and the ability to work independently and efficiently.',
    industry: 'Home Maintenance',
    location: 'Seattle, WA',
    experience: 'Entry level',
    environment: 'Onsite',
    salary: '$50,000-$60,000',
    employmentType: 'Full time',
  },
  {
    id: 14,
    title: 'Ornithologist',
    description: 'We are seeking a passionate and knowledgeable Ornithologist to join our team. You will be responsible for studying birds in their natural habitats, conducting research and collecting data, and educating the public about bird conservation. Successful candidates will have a degree in ornithology or related field, several years of experience in the field, and a love of birds and their habitats.',
    industry: 'Nature & Environment',
    location: 'Denver, CO',
    experience: 'Mid level',
    environment: 'Onsite',
    salary: '$80,000-$100,000',
    employmentType: 'Full time',
  },
  {
    id: 15,
    title: 'Pawthor',
    description: 'Write inspiring books about feline heroes and their adventures',
    industry: 'Arts & Literature',
    location: 'New York, NY',
    experience: 'Senior Level',
    environment: 'Onsite',
    salary: '$200,000 - $250,000',
    employmentType: 'Full Time',
  },
  {
    id: 16,
    title: 'Horticulturist',
    description: 'Design and maintain beautiful gardens for cat clients',
    industry: 'Horticulture & Botany',
    location: 'Portland, OR',
    experience: 'Mid Level',
    environment: 'Mixed',
    salary: '$80,000 - $100,000',
    employmentType: 'Full Time',
  },
  {
    id: 17,
    title: 'Lap Warmer',
    description: 'Provide warmth and comfort to cat owners by sitting on their laps',
    industry: 'Home Maintenance',
    location: 'San Francisco, CA',
    experience: 'Entry Level',
    environment: 'Onsite',
    salary: '$50,000 - $60,000',
    employmentType: 'Part Time',
  },
  {
    id: 18,
    title: 'Pest Exterminator',
    description: 'Eliminate pests from homes and businesses to create a safe and clean environment',
    industry: 'Home Maintenance',
    location: 'Miami, FL',
    experience: 'Mid Level',
    environment: 'Onsite',
    salary: '$90,000 - $120,000',
    employmentType: 'Full Time',
  },
  {
    id: 19,
    title: 'Ornithologist',
    description: 'Study birds and their habitats to better understand and protect them',
    industry: 'Nature & Environment',
    location: 'Seattle, WA',
    experience: 'Senior Level',
    environment: 'Mixed',
    salary: '$250,000 - $300,000',
    employmentType: 'Full Time',
  },
  {
    id: 20,
    title: 'Private Investigator',
    description: 'Uncover secrets and solve mysteries for feline clients',
    industry: 'Security & Safety',
    location: 'Los Angeles, CA',
    experience: 'Executive Level',
    environment: 'Mixed',
    salary: '$400,000 - $500,000',
    employmentType: 'Full Time',
  },
];

export default jobListingsData;
